# GitHub Sponsors configuration for x0v3rt
# This file enables the "Sponsor" button on your repository

# GitHub username for GitHub Sponsors
github: J0n-H4rr150n

# Open Collective username
open_collective: # Replace with your Open Collective username if you use it

# Ko-fi username
ko_fi: # Replace with your Ko-fi username if you use it

# Tidelift package name
tidelift: # Replace with your Tidelift package name if you use it

# Community Bridge project name
community_bridge: # Replace with your Community Bridge project name if you use it

# LiberaPay username
liberapay: # Replace with your LiberaPay username if you use it

# IssueHunt username
issuehunt: # Replace with your IssueHunt username if you use it

# Otechie username
otechie: # Replace with your Otechie username if you use it

# Buy Me a Coffee username
buy_me_a_coffee: j0nh4rr150n

# Patreon username
patreon: # Replace with your Patreon username if you use it

# Custom funding URLs (up to 4)
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.paypal.me/...', 'https://www.buymeacoffee.com/...']
