name: Feature Request
description: Propose a new idea
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What is your feature idea?
    validations:
      required: true
